name       : python-rope
version    : 0.11.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/r/rope/rope-0.11.0.tar.gz : a108c445e1cd897fe19272ab7877d172e7faf3d4148c80e7d20faba42ea8f7b2
license    : GPL-2.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

    chmod 00644 $installdir/usr/lib/python*/site-packages/rope-$version-py*.egg-info/*
check     : |
    %python_test
    %python3_test
