name       : python-rope
version    : 0.19.0
release    : 9
source     :
    - https://github.com/python-rope/rope/archive/refs/tags/0.19.0.tar.gz : e74e4eb623f5d0a5b3e6eea20297e71d10e3170b630fe0b8c4963d98d99a63e5
homepage   : https://github.com/python-rope/rope
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
