name       : python-rope
version    : 1.18.0
release    : 8
source     :
    - https://github.com/python-rope/rope/archive/0.18.0.tar.gz : a8938e7e5fa60fc567d854762e3d0309bd355186d4ff3e5d39811e8df2f6a7ac
homepage   : https://github.com/python-rope/rope
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
