name       : python-rope
version    : 0.10.7
release    : 1
source     :
    - https://github.com/python-rope/rope/archive/0.10.7.tar.gz : 4426d16686774f2b3d0431e5e54e7e261eab967e9e50e0af7fdaf95436057d74
license    : GPL-2.0
component  : programming.python
summary    : Rope is a python refactoring library.
description: |
    Rope is a python refactoring library.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
