name       : python-rope
version    : 1.6.0
release    : 16
source     :
    - https://github.com/python-rope/rope/archive/refs/tags/1.6.0.tar.gz : 5ce2cdae8fa3d08a4f6f308f172037e8cb7a74c626e9e64ea9f52a1a23d5c22c
homepage   : https://github.com/python-rope/rope
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
builddeps  :
    - python-packaging    # check
    - python-platformdirs # check
    - python-pytoolconfig # check
    - python-tomli        # check
    - python-pytest       # check
rundeps    :
    - python-pytoolconfig
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -v
