name       : python-rope
version    : 0.20.0
release    : 11
source     :
    - https://github.com/python-rope/rope/archive/refs/tags/0.20.0.tar.gz : 83bd664e41fceeb7506d95781ec8cbe0e4c957d9602220e52896793507dc1384
homepage   : https://github.com/python-rope/rope
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
