name       : python-rope
version    : 0.14.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/fc/18/df49bd6937eb20c90d69292120d6228b509e8e2d2107bd5755ec4c259de3/rope-0.14.0.tar.gz : c5c5a6a87f7b1a2095fb311135e2a3d1f194f5ecb96900fdd0a9100881f48aaf
license    : GPL-2.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

    chmod 00644 $installdir/usr/lib/python*/site-packages/rope-$version-py*.egg-info/*
check      : |
    %python_test
    #python3_test
