name       : python-rope
version    : 0.17.0
release    : 7
source     :
    - https://github.com/python-rope/rope/archive/0.17.0.tar.gz : 43a0150a431639ac63a5b4e0520a31eda6d7d0c9d41345f21316a848d6b8e738
homepage   : https://github.com/python-rope/rope
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Rope is a python refactoring library
description: |
    A python refactoring library. It provides features like refactorings and coding assists.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
